# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('code', models.CharField(max_length=256)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
